/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculatorapp;

/**
 *
 * @author pc
 */
public class calculatorFrame extends javax.swing.JFrame {
    calculator calc = new calculator();
   

    /**
     * Creates new form calculatorFrame
     */
    public calculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnSquare = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnPercentage = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumber2 = new javax.swing.JTextField();
        txtNumber1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 170, 30));

        btnFactorial.setText("!");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnFactorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 60, 30));

        btnSquare.setText(" ^2");
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });
        jPanel1.add(btnSquare, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 60, 30));

        btnPower.setText("^");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 60, 30));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 170, 30));

        btnTan.setText("tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });
        jPanel1.add(btnTan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 50, 30));

        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 50, 30));

        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });
        jPanel1.add(btnSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 50, 30));

        btnPercentage.setText("%");
        btnPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentageActionPerformed(evt);
            }
        });
        jPanel1.add(btnPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 60, 30));

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 60, 30));

        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 60, 30));

        btnSubtract.setText("-");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 60, 30));

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 60, 30));
        jPanel1.add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 120, 60));

        jLabel4.setText("Result");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 20));
        jPanel1.add(txtNumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, 30));
        jPanel1.add(txtNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 120, 30));

        jLabel3.setText("Enter the 2nd number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setText("Enter the 1st number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot 2025-09-01 081030.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
               // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double n2 = Double.parseDouble(txtNumber2.getText());
        double result = calc.add(n1, n2);
        txtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double n2 = Double.parseDouble(txtNumber2.getText());
        double result = calc.subtract(n1, n2);
        txtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double n2 = Double.parseDouble(txtNumber2.getText());
        double result = calc.multiply(n1, n2);
        txtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
        try {
            double n1 = Double.parseDouble(txtNumber1.getText());
            double n2 = Double.parseDouble(txtNumber2.getText());
            double result = calc.divide(n1, n2);
            txtResult.setText(String.valueOf(result));
        } catch (ArithmeticException e) {
            txtResult.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentageActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double n2 = Double.parseDouble(txtNumber2.getText());
        double result = calc.percentage(n1, n2);
        txtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_btnPercentageActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double result = calc.sin(n1);
        txtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double result = calc.cos(n1);
        txtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double result = calc.tan(n1);
        txtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String current = txtResult.getText();
        if (!current.isEmpty()) {
            txtResult.setText(current.substring(0, current.length() - 1));
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double result = calc.square(n1);
        txtResult.setText(String.valueOf(result));
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txtNumber1.getText());
        double n2 = Double.parseDouble(txtNumber2.getText());  // exponent
        double result = calc.power(n1, n2);
        txtResult.setText(String.valueOf(result));

    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        // TODO add your handling code here:
        int n1 = Integer.parseInt(txtNumber1.getText());
        long result = calc.factorial(n1);
        txtResult.setText(String.valueOf(result));

    }//GEN-LAST:event_btnFactorialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtNumber1.setText("");
        txtNumber2.setText("");
         txtResult.setText("");
        txtNumber1.requestFocus();  // cursor wapas pehle textbox me aa jayega

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPercentage;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumber1;
    private javax.swing.JTextField txtNumber2;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
