/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzaapp;
import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author pc
 */
public class ToppingFrame extends javax.swing.JFrame {
    JCheckBox[] toppingBoxes;

    /**
     * Creates new form ToppingFrame
     */
    public ToppingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox6.setBackground(new java.awt.Color(255, 51, 51));
        jCheckBox6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCheckBox6.setText("Jalapenos");
        jCheckBox6.setOpaque(true);
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(255, 51, 51));
        jCheckBox5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCheckBox5.setText("Tomatoes");
        jCheckBox5.setOpaque(true);
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(255, 51, 51));
        jCheckBox4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCheckBox4.setText("Capsicum");
        jCheckBox4.setOpaque(true);
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(255, 51, 51));
        jCheckBox3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCheckBox3.setText("Onions");
        jCheckBox3.setOpaque(true);
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 51, 51));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCheckBox2.setText("Mushrooms");
        jCheckBox2.setOpaque(true);
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 51, 51));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCheckBox1.setText("Olives");
        jCheckBox1.setOpaque(true);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton3.setText("Clear ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Choose Toppings");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 450, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot 2025-09-08 070311.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 590, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /*jButton1.addActionListener(e -> {
    // peechay SauceFrame kholna hai
    new SauceFrame().setVisible(true);
    dispose(); // current frame band ho jaye
});*/
    new SauceFrame().setVisible(true);
    dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /*jButton2.addActionListener(e -> {
    ArrayList<String> selectedToppings = new ArrayList<>();

    if (jCheckBox1.isSelected()) selectedToppings.add("Olives");
    if (jCheckBox2.isSelected()) selectedToppings.add("Mushrooms");
    if (jCheckBox3.isSelected()) selectedToppings.add("Onions");
    if (jCheckBox4.isSelected()) selectedToppings.add("Capsicum");
    if (jCheckBox5.isSelected()) selectedToppings.add("Tomatoes");
    if (jCheckBox6.isSelected()) selectedToppings.add("Jalapenos");

    if (selectedToppings.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select at least one topping!");
    } else {
        JOptionPane.showMessageDialog(this, "Selected Toppings: " + selectedToppings);
        new CheeseFrame().setVisible(true); // next frame kholna
        dispose();
    }
});*/
 ArrayList<String> selectedToppings = new ArrayList<>();

    if (jCheckBox1.isSelected()) selectedToppings.add("Olives");
    if (jCheckBox2.isSelected()) selectedToppings.add("Mushrooms");
    if (jCheckBox3.isSelected()) selectedToppings.add("Onions");
    if (jCheckBox4.isSelected()) selectedToppings.add("Capsicum");
    if (jCheckBox5.isSelected()) selectedToppings.add("Tomatoes");
    if (jCheckBox6.isSelected()) selectedToppings.add("Jalapenos");

    if (selectedToppings.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select at least one topping!");
    } else {
        // yahan Items class me save karna
        Items.selectedTopping = String.join(", ", selectedToppings);

        JOptionPane.showMessageDialog(this, "Selected Toppings: " + Items.selectedTopping);
        new CheeseFrame().setVisible(true); // next frame open hoga
        dispose();
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       // jButton3.addActionListener(e -> {
    jCheckBox1.setSelected(false);
    jCheckBox2.setSelected(false);
    jCheckBox3.setSelected(false);
    jCheckBox4.setSelected(false);
    jCheckBox5.setSelected(false);
    jCheckBox6.setSelected(false);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.addActionListener(e -> {
    System.exit(0);
});

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToppingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToppingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToppingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToppingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToppingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
