/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz.application.mcq.based;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Arrays;//////////////////////////////////////


/**
 *
 * @author pc
 */
public class QuizFrame extends javax.swing.JFrame {
    ArrayList<Question> questions = new ArrayList<>();
    int currentIndex = 0;
    int score = 0;
    int[] selected; ////////////////////////////////////
    
    

    /**
     * Creates new form QuizFrame
     */
    public QuizFrame() {
        initComponents();
      questions.add(new Question(
        "Which keyword is used to inherit a class in Java?", 
        new String[]{"this", "super", "extends", "implements"}, 
        "extends"
    ));

    questions.add(new Question(
        "Which of the following is NOT an OOP concept?", 
        new String[]{"Encapsulation", "Abstraction", "Polymorphism", "Compilation"}, 
        "Compilation"
    ));

    questions.add(new Question(
        "Which method is the entry point of a Java program?", 
        new String[]{"start()", "run()", "main()", "execute()"}, 
        "main()"
    ));

    questions.add(new Question(
        "Which operator is used for object creation in Java?", 
        new String[]{"create", "new", "malloc", "init"}, 
        "new"
    ));

    questions.add(new Question(
        "Which collection class allows key-value pairs in Java?", 
        new String[]{"ArrayList", "HashMap", "HashSet", "Vector"}, 
        "HashMap"
    ));

    // Answers tracking array initialize
    selected = new int[questions.size()];
    Arrays.fill(selected, -1);

    loadQuestion(0);///////////////////////////////////////////
    }
    private void loadQuestion(int index) {
        Question q = questions.get(index);
     questionLabel.setText((index + 1) + ". " + q.getQuestion());
    option1.setText(q.getOptions()[0]);
    option2.setText(q.getOptions()[1]);
    option3.setText(q.getOptions()[2]);
    option4.setText(q.getOptions()[3]);

    // use NetBeans-created ButtonGroup name
    buttonGroup1.clearSelection();

    // restore previous selection if any
    if (selected != null && selected.length > index) {
        if (selected[index] == 0) option1.setSelected(true);
        else if (selected[index] == 1) option2.setSelected(true);
        else if (selected[index] == 2) option3.setSelected(true);
        else if (selected[index] == 3) option4.setSelected(true);
    }
    }
    private void saveSelected() {
    if (option1.isSelected()) selected[currentIndex] = 0;
    else if (option2.isSelected()) selected[currentIndex] = 1;
    else if (option3.isSelected()) selected[currentIndex] = 2;
    else if (option4.isSelected()) selected[currentIndex] = 3;
    else selected[currentIndex] = -1;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        option4 = new javax.swing.JRadioButton();
        option3 = new javax.swing.JRadioButton();
        option2 = new javax.swing.JRadioButton();
        option1 = new javax.swing.JRadioButton();
        questionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        submitButton.setBackground(new java.awt.Color(255, 153, 153));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        nextButton.setBackground(new java.awt.Color(255, 153, 153));
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 80, -1));

        prevButton.setBackground(new java.awt.Color(255, 153, 153));
        prevButton.setText("Previous");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });
        jPanel1.add(prevButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        buttonGroup1.add(option4);
        option4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        option4.setText("jRadioButton4");
        jPanel1.add(option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        buttonGroup1.add(option3);
        option3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        option3.setText("jRadioButton3");
        option3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3ActionPerformed(evt);
            }
        });
        jPanel1.add(option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        buttonGroup1.add(option2);
        option2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        option2.setText("jRadioButton2");
        jPanel1.add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        buttonGroup1.add(option1);
        option1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        option1.setText("jRadioButton1");
        jPanel1.add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        questionLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        questionLabel.setText("jLabel2");
        jPanel1.add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 400, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Pictures\\Screenshots\\Screenshot 2025-09-07 080543.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // TODO add your handling code here:
        saveSelected();
    if (currentIndex > 0) {
        currentIndex--;
        loadQuestion(currentIndex);
    }
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
         saveSelected();
    if (currentIndex < questions.size() - 1) {
        currentIndex++;
        loadQuestion(currentIndex);
    }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
         // save current before calculating
    saveSelected();

    score = 0;
    for (int i = 0; i < questions.size(); i++) {
        if (selected[i] != -1) {
            String chosen = questions.get(i).getOptions()[selected[i]];
            if (chosen.equals(questions.get(i).getCorrectAnswer())) score++;
        }
    }

    JOptionPane.showMessageDialog(this, "Your Score: " + score + " / " + questions.size());
    }//GEN-LAST:event_submitButtonActionPerformed

    private void option3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // Sab answers reset karna
    for (int i = 0; i < selected.length; i++) {
        selected[i] = -1; // har question ke liye -1 matlab no selection
    }

    // Current question ka option bhi clear kar do
    buttonGroup1.clearSelection();

    // Pehle question se start karna
    currentIndex = 0;
    loadQuestion(currentIndex);

    JOptionPane.showMessageDialog(this, "All answers have been cleared!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton option1;
    private javax.swing.JRadioButton option2;
    private javax.swing.JRadioButton option3;
    private javax.swing.JRadioButton option4;
    private javax.swing.JButton prevButton;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
